#include "pin.h"

//********* PIN DEFINITIONS *********// 

//PIN_INIT(GPIOA, 0, xxx)
//PIN_INIT(GPIOA, 1, xxx)
//PIN_INIT(GPIOA, 2, xxx)
//PIN_INIT(GPIOA, 3, xxx)
//PIN_INIT(GPIOA, 4, xxx)
PIN_INIT(GPIOA, 5, SPI1_SCK)
//PIN_INIT(GPIOA, 6, xxx)
//PIN_INIT(GPIOA, 7, xxx)
//PIN_INIT(GPIOA, 8, xxx)
//PIN_INIT(GPIOA, 9, xxx)
//PIN_INIT(GPIOA, 10, xxx)
//PIN_INIT(GPIOA, 11, xxx)
PIN_INIT(GPIOA, 12, TIMER2)
//PIN_INIT(GPIOA, 13, xxx)
//PIN_INIT(GPIOA, 14, xxx)
//PIN_INIT(GPIOA, 15, xxx)

//PIN_INIT(GPIOB, 0, xxx)
//PIN_INIT(GPIOB, 1, xxx)
//PIN_INIT(GPIOB, 2, xxx)
//PIN_INIT(GPIOB, 3, xxx)
//PIN_INIT(GPIOB, 4, xxx)
//PIN_INIT(GPIOB, 5, xxx)
PIN_INIT(GPIOB, 6, TX)
//PIN_INIT(GPIOB, 7, xxx)
//PIN_INIT(GPIOB, 6, xxx)
//PIN_INIT(GPIOB, 8, xxx)
//PIN_INIT(GPIOB, 9, xxx)
//PIN_INIT(GPIOB, 10, xxx)
//PIN_INIT(GPIOB, 11, xxx)
//PIN_INIT(GPIOB, 12, xxx)
//PIN_INIT(GPIOB, 13, xxx)
//PIN_INIT(GPIOB, 14, xxx)
//PIN_INIT(GPIOB, 15, xxx)

//PIN_INIT(GPIOC, 0, xxx)
//PIN_INIT(GPIOC, 1, xxx)
//PIN_INIT(GPIOC, 2, xxx)
PIN_INIT(GPIOC, 3, adc)
//PIN_INIT(GPIOC, 4, xxx)
//PIN_INIT(GPIOC, 5, xxx)
//PIN_INIT(GPIOC, 6, xxx)
//PIN_INIT(GPIOC, 7, xxx)
//PIN_INIT(GPIOC, 8, xxx)
//PIN_INIT(GPIOC, 9, xxx)
//PIN_INIT(GPIOC, 10, xxx)
//PIN_INIT(GPIOC, 11, xxx)
//PIN_INIT(GPIOC, 12, xxx)
//PIN_INIT(GPIOC, 13, xxx)
//PIN_INIT(GPIOC, 14, xxx)
//PIN_INIT(GPIOC, 15, ADC2)

//PIN_INIT(GPIOD, 0, xxx)
PIN_INIT(GPIOD, 1, TIMER)
//PIN_INIT(GPIOD, 2, xxx)
//Number of GPIO: 51
